### PR TITLE
Edit Options

### PR DESCRIPTION
**Pull request by rgerd**
Work-in-progress PR for adding a view that appears on buttons to provide editing options. You may provide feedback but please do not approve these changes yet.

### CODE REVIEW

**Comment by rgerd** [comment]
Nice catch! Thank you for doing proper QA!

**Comment by rgerd** [comment]
By the way, when you want to update your branch to sit on top of mine, do this:
```
git fetch
git checkout rgerd/edit-options && git pull
git checkout [your_branch]
git rebase origin/rgerd/edit-options
```
Hopefully it works. If there are merge conflicts, go into the project and resolve the conflicts manually. Once the conflicts are resolved and everything builds correctly, run
`git add . && git rebase --continue`
Finally if things aren't going right, you can just do 
`git rebase --abort` 
and I can go in and do it myself.

**Comment by jaspalsinghsaini** [comment]
@rgerd There is one more small bug: If we modify the grid-size when in the edit-mode, then the selected button in edit-mode ALWAYS remains in the UI when we exit the settings menu. One sequence of events for buggy display: enter edit-mode -> tap on "thank you" card -> increase grid-size.

**Comment by jaspalsinghsaini** [comment]
simulator screen shot - ipad air - 2018-04-22 at 16 00 35

**Pull request merged**
